const awsServerlessExpress = require("aws-serverless-express");
const app = require("./app");

const server = awsServerlessExpress.createServer(app);

exports.handler = (event, context) => {
  console.log(`EVENT: ${JSON.stringify(event)}`);
  awsServerlessExpress.proxy(server, event, context);
};
//All of the code above this line was generated by amplify and aws
const request = require("request");
const cheerio = require("cheerio");
const url =
  "https://bulletin.temple.edu/undergraduate/science-technology/computer-information-science/computer-science-bs/#academicplantext";

request(url, function(err, resp, html) {
  if (!err) {
    const $ = cheerio.load(html);
    console.log(html);
  }
});
